-- 01_account_setup.sql
-- Setup account-level objects: Role, Database, Warehouse, Compute Pool
-- Variables are expected to be set by the shell script before execution

USE ROLE ACCOUNTADMIN;

-- 1. Create Role
CREATE ROLE IF NOT EXISTS IDENTIFIER($PROJECT_ROLE)
    COMMENT = 'Role for MMM project';

SET MY_USER = (SELECT CURRENT_USER());
GRANT ROLE IDENTIFIER($PROJECT_ROLE) TO USER IDENTIFIER($MY_USER);
GRANT ROLE IDENTIFIER($PROJECT_ROLE) TO ROLE SYSADMIN;

-- 2. Create Database
CREATE DATABASE IF NOT EXISTS IDENTIFIER($FULL_PREFIX)
    COMMENT = 'Database for Global B2B MMM Demo';

-- Grant ownership
GRANT OWNERSHIP ON DATABASE IDENTIFIER($FULL_PREFIX) 
    TO ROLE IDENTIFIER($PROJECT_ROLE) COPY CURRENT GRANTS;

-- 3. Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($PROJECT_WH)
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'Warehouse for MMM project';

GRANT OWNERSHIP ON WAREHOUSE IDENTIFIER($PROJECT_WH) 
    TO ROLE IDENTIFIER($PROJECT_ROLE) COPY CURRENT GRANTS;

-- 4. Create Compute Pool
-- Note: Requires ACCOUNTADMIN
CREATE COMPUTE POOL IF NOT EXISTS IDENTIFIER($PROJECT_COMPUTE_POOL)
    MIN_NODES = 1
    MAX_NODES = 1
    INSTANCE_FAMILY = CPU_X64_S
    AUTO_RESUME = TRUE
    AUTO_SUSPEND_SECS = 300
    COMMENT = 'Compute pool for MMM Notebooks';

GRANT OWNERSHIP ON COMPUTE POOL IDENTIFIER($PROJECT_COMPUTE_POOL) 
    TO ROLE IDENTIFIER($PROJECT_ROLE) COPY CURRENT GRANTS;

SELECT 'Account setup complete.' as status;

