-- 02_schema_setup.sql
-- Setup schema-level objects: Schemas, Tables, Views, Stages
-- Expected context: Role = Project Role, Database = Project Database

-- 1. Create Schemas
CREATE SCHEMA IF NOT EXISTS RAW COMMENT = 'Landing zone for raw data';
CREATE SCHEMA IF NOT EXISTS ATOMIC COMMENT = 'Normalized and clean data';
CREATE SCHEMA IF NOT EXISTS MMM COMMENT = 'Analytics Mart for Modeling and App';

-- 2. Create Stages
USE SCHEMA ATOMIC;
CREATE STAGE IF NOT EXISTS DATA_STAGE 
    DIRECTORY = (ENABLE = TRUE) 
    COMMENT = 'Stage for raw data files';

CREATE STAGE IF NOT EXISTS MODELS_STAGE 
    DIRECTORY = (ENABLE = TRUE) 
    COMMENT = 'Stage for ML models and notebooks';

-- 3. Create File Formats
CREATE FILE FORMAT IF NOT EXISTS CSV_FORMAT
    TYPE = 'CSV'
    COMPRESSION = 'AUTO'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

-- 4. Create Tables in RAW Schema
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS SPRINKLR_DAILY (
    DATE DATE,
    CAMPAIGN_ID VARCHAR(50),
    CHANNEL VARCHAR(50),
    SPEND_AMT FLOAT,
    IMPRESSIONS NUMBER,
    CLICKS NUMBER,
    VIDEO_VIEWS_50 NUMBER
);

CREATE TABLE IF NOT EXISTS SFDC_OPPORTUNITIES (
    OPPORTUNITY_ID VARCHAR(50),
    ACCOUNT_NAME VARCHAR(255),
    LEAD_SOURCE_CAMPAIGN VARCHAR(50),
    STAGE VARCHAR(50),
    AMOUNT_USD FLOAT,
    CREATED_DATE DATE,
    CLOSE_DATE DATE,
    BUSINESS_GROUP VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS SAP_ACTUALS (
    INVOICE_ID VARCHAR(50),
    BOOKED_REVENUE FLOAT,
    PROFIT_CENTER VARCHAR(50),
    POSTING_DATE DATE,
    OPPORTUNITY_ID VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS MACRO_INDICATORS (
    DATE DATE,
    PMI_INDEX FLOAT,
    COMPETITOR_SOV FLOAT,
    REGION VARCHAR(50)
);

-- 5. Create Tables in ATOMIC Schema
USE SCHEMA ATOMIC;

-- Marketing Campaign (Taxonomy)
CREATE TABLE IF NOT EXISTS MARKETING_CAMPAIGN (
    CAMPAIGN_ID VARCHAR(50) NOT NULL COMMENT 'Unique Campaign ID',
    CAMPAIGN_NAME VARCHAR(255) COMMENT 'Taxonomy Name',
    BUSINESS_GROUP VARCHAR(50),
    REGION VARCHAR(50),
    DIVISION VARCHAR(50),
    CAMPAIGN_TYPE VARCHAR(50),
    CHANNEL VARCHAR(50),
    START_DATE DATE,
    PRIMARY KEY (CAMPAIGN_ID)
);

-- Media Spend Daily
CREATE TABLE IF NOT EXISTS MEDIA_SPEND_DAILY (
    SPEND_DATE DATE NOT NULL,
    CAMPAIGN_ID VARCHAR(50) NOT NULL,
    CHANNEL VARCHAR(50),
    SPEND_AMOUNT FLOAT,
    IMPRESSIONS NUMBER,
    CLICKS NUMBER,
    VIDEO_VIEWS NUMBER,
    FOREIGN KEY (CAMPAIGN_ID) REFERENCES MARKETING_CAMPAIGN(CAMPAIGN_ID)
);

-- Opportunity (Standard)
CREATE TABLE IF NOT EXISTS OPPORTUNITY (
    OPPORTUNITY_ID VARCHAR(50) NOT NULL,
    OPPORTUNITY_NAME VARCHAR(255), -- Account Name
    CAMPAIGN_ID VARCHAR(50),
    STAGE_NAME VARCHAR(50),
    AMOUNT FLOAT,
    CREATED_DATE DATE,
    CLOSE_DATE DATE,
    BUSINESS_UNIT VARCHAR(50),
    PRIMARY KEY (OPPORTUNITY_ID),
    FOREIGN KEY (CAMPAIGN_ID) REFERENCES MARKETING_CAMPAIGN(CAMPAIGN_ID)
);

-- Financial Result (Revenue)
CREATE TABLE IF NOT EXISTS ACTUAL_FINANCIAL_RESULT (
    INVOICE_ID VARCHAR(50) NOT NULL,
    OPPORTUNITY_ID VARCHAR(50),
    REVENUE_AMOUNT FLOAT,
    POSTING_DATE DATE,
    PROFIT_CENTER VARCHAR(50),
    PRIMARY KEY (INVOICE_ID),
    FOREIGN KEY (OPPORTUNITY_ID) REFERENCES OPPORTUNITY(OPPORTUNITY_ID)
);

-- Market Signals
CREATE TABLE IF NOT EXISTS MARKET_SIGNAL (
    SIGNAL_DATE DATE NOT NULL,
    SIGNAL_TYPE VARCHAR(50) COMMENT 'PMI, SOV, etc.',
    SIGNAL_VALUE FLOAT,
    REGION VARCHAR(50)
);

-- 6. Create Views in MMM Schema
USE SCHEMA MMM;

-- Weekly Aggregated Input for Robyn
CREATE OR REPLACE VIEW V_MMM_INPUT_WEEKLY AS
WITH WEEKLY_SPEND AS (
    SELECT 
        DATE_TRUNC('WEEK', SPEND_DATE) AS WEEK_START,
        CHANNEL,
        SUM(SPEND_AMOUNT) AS TOTAL_SPEND,
        SUM(IMPRESSIONS) AS TOTAL_IMPRESSIONS,
        SUM(CLICKS) AS TOTAL_CLICKS
    FROM ATOMIC.MEDIA_SPEND_DAILY
    GROUP BY 1, 2
),
WEEKLY_REVENUE AS (
    SELECT
        DATE_TRUNC('WEEK', POSTING_DATE) AS WEEK_START,
        SUM(REVENUE_AMOUNT) AS TOTAL_REVENUE
    FROM ATOMIC.ACTUAL_FINANCIAL_RESULT
    GROUP BY 1
),
WEEKLY_SIGNALS AS (
    SELECT
        DATE_TRUNC('WEEK', SIGNAL_DATE) AS WEEK_START,
        AVG(CASE WHEN SIGNAL_TYPE = 'PMI' THEN SIGNAL_VALUE END) AS AVG_PMI,
        AVG(CASE WHEN SIGNAL_TYPE = 'SOV' THEN SIGNAL_VALUE END) AS AVG_SOV
    FROM ATOMIC.MARKET_SIGNAL
    GROUP BY 1
)
SELECT
    COALESCE(S.WEEK_START, R.WEEK_START) AS WEEK_START,
    S.CHANNEL,
    ZEROIFNULL(S.TOTAL_SPEND) AS SPEND,
    ZEROIFNULL(S.TOTAL_IMPRESSIONS) AS IMPRESSIONS,
    ZEROIFNULL(S.TOTAL_CLICKS) AS CLICKS,
    ZEROIFNULL(R.TOTAL_REVENUE) AS REVENUE, -- Note: This is simplified. Ideally revenue is attributed.
    SIG.AVG_PMI,
    SIG.AVG_SOV
FROM WEEKLY_SPEND S
FULL OUTER JOIN WEEKLY_REVENUE R ON S.WEEK_START = R.WEEK_START
LEFT JOIN WEEKLY_SIGNALS SIG ON S.WEEK_START = SIG.WEEK_START;

-- ROI by Channel View (Simple Attribution for Dashboard)
CREATE OR REPLACE VIEW V_ROI_BY_CHANNEL AS
SELECT
    C.CHANNEL,
    SUM(S.SPEND_AMOUNT) AS TOTAL_SPEND,
    SUM(R.REVENUE_AMOUNT) AS ATTRIBUTED_REVENUE,
    DIV0(SUM(R.REVENUE_AMOUNT), SUM(S.SPEND_AMOUNT)) AS ROAS
FROM ATOMIC.MEDIA_SPEND_DAILY S
JOIN ATOMIC.MARKETING_CAMPAIGN C ON S.CAMPAIGN_ID = C.CAMPAIGN_ID
LEFT JOIN ATOMIC.OPPORTUNITY O ON C.CAMPAIGN_ID = O.CAMPAIGN_ID
LEFT JOIN ATOMIC.ACTUAL_FINANCIAL_RESULT R ON O.OPPORTUNITY_ID = R.OPPORTUNITY_ID
GROUP BY 1;

-- Results tables for Model Output
CREATE TABLE IF NOT EXISTS MODEL_RESULTS (
    MODEL_VERSION VARCHAR(50),
    CHANNEL VARCHAR(50),
    COEFF_WEIGHT FLOAT,
    ROI FLOAT,
    MARGINAL_ROI FLOAT,
    OPTIMAL_SPEND FLOAT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RESPONSE_CURVES (
    MODEL_VERSION VARCHAR(50),
    CHANNEL VARCHAR(50),
    SPEND FLOAT,
    PREDICTED_REVENUE FLOAT
);

SELECT 'Schema setup complete.' as status;

