-- 03_load_data.sql
-- Load data from Stage to RAW and then to ATOMIC
-- Expected context: Role = Project Role, Database = Project Database

USE SCHEMA RAW;

-- 0. Truncate RAW tables to ensure fresh load
TRUNCATE TABLE IF EXISTS SPRINKLR_DAILY;
TRUNCATE TABLE IF EXISTS SFDC_OPPORTUNITIES;
TRUNCATE TABLE IF EXISTS SAP_ACTUALS;
TRUNCATE TABLE IF EXISTS MACRO_INDICATORS;
TRUNCATE TABLE IF EXISTS RAW_CAMPAIGN_METADATA;

-- 1. Copy into RAW Tables (FORCE=TRUE to reload even if files were previously loaded)
COPY INTO SPRINKLR_DAILY
FROM @ATOMIC.DATA_STAGE/sprinklr_spend.csv
FILE_FORMAT = (FORMAT_NAME = ATOMIC.CSV_FORMAT)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

COPY INTO SFDC_OPPORTUNITIES
FROM @ATOMIC.DATA_STAGE/salesforce_opps.csv
FILE_FORMAT = (FORMAT_NAME = ATOMIC.CSV_FORMAT)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

COPY INTO SAP_ACTUALS
FROM @ATOMIC.DATA_STAGE/sap_revenue.csv
FILE_FORMAT = (FORMAT_NAME = ATOMIC.CSV_FORMAT)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

COPY INTO MACRO_INDICATORS
FROM @ATOMIC.DATA_STAGE/macro_indicators.csv
FILE_FORMAT = (FORMAT_NAME = ATOMIC.CSV_FORMAT)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

-- 2. Transform and Load to ATOMIC

-- Marketing Campaigns (Extract from Metadata or derive)
-- Note: Our gen script created campaign_metadata.csv, but we didn't create a RAW table for it.
-- We can derive it from the Spend table or load the metadata file. 
-- Let's assume we load the metadata file if available, or just derive distinct IDs.
-- Ideally we load campaign_metadata.csv. Let's add a COPY for it.

CREATE TABLE IF NOT EXISTS RAW_CAMPAIGN_METADATA (
    CAMPAIGN_ID VARCHAR(50),
    CAMPAIGN_NAME VARCHAR(255),
    BG VARCHAR(50),
    REGION VARCHAR(50),
    DIVISION VARCHAR(50),
    TYPE VARCHAR(50),
    CHANNEL VARCHAR(50),
    START_DATE DATE,
    DURATION NUMBER
);

COPY INTO RAW_CAMPAIGN_METADATA
FROM @ATOMIC.DATA_STAGE/campaign_metadata.csv
FILE_FORMAT = (FORMAT_NAME = ATOMIC.CSV_FORMAT)
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

INSERT OVERWRITE INTO ATOMIC.MARKETING_CAMPAIGN_FLAT (
    CAMPAIGN_ID, CAMPAIGN_NAME, BUSINESS_GROUP, REGION, DIVISION, CAMPAIGN_TYPE, CHANNEL, START_DATE
)
SELECT 
    CAMPAIGN_ID, CAMPAIGN_NAME, BG, REGION, DIVISION, TYPE, CHANNEL, START_DATE
FROM RAW_CAMPAIGN_METADATA;

-- Media Spend
INSERT OVERWRITE INTO ATOMIC.MEDIA_SPEND_DAILY (
    SPEND_DATE, CAMPAIGN_ID, CHANNEL, SPEND_AMOUNT, IMPRESSIONS, CLICKS, VIDEO_VIEWS
)
SELECT 
    DATE, CAMPAIGN_ID, CHANNEL, SPEND_AMT, IMPRESSIONS, CLICKS, VIDEO_VIEWS_50
FROM SPRINKLR_DAILY;

-- Opportunities
INSERT OVERWRITE INTO ATOMIC.OPPORTUNITY (
    OPPORTUNITY_ID, OPPORTUNITY_NAME, CAMPAIGN_ID, STAGE_NAME, AMOUNT, CREATED_DATE, CLOSE_DATE, BUSINESS_UNIT
)
SELECT 
    OPPORTUNITY_ID, ACCOUNT_NAME, LEAD_SOURCE_CAMPAIGN, STAGE, AMOUNT_USD, CREATED_DATE, CLOSE_DATE, BUSINESS_GROUP
FROM SFDC_OPPORTUNITIES;

-- Financials
INSERT OVERWRITE INTO ATOMIC.ACTUAL_FINANCIAL_RESULT (
    INVOICE_ID, OPPORTUNITY_ID, REVENUE_AMOUNT, POSTING_DATE, PROFIT_CENTER
)
SELECT 
    INVOICE_ID, OPPORTUNITY_ID, BOOKED_REVENUE, POSTING_DATE, PROFIT_CENTER
FROM SAP_ACTUALS;

-- Signals (Unpivot if necessary, but our raw is already long-ish or we split it)
INSERT OVERWRITE INTO ATOMIC.MARKET_SIGNAL (
    SIGNAL_DATE, SIGNAL_TYPE, SIGNAL_VALUE, REGION
)
SELECT DATE, 'PMI', PMI_INDEX, REGION FROM MACRO_INDICATORS
UNION ALL
SELECT DATE, 'SOV', COMPETITOR_SOV, REGION FROM MACRO_INDICATORS;

SELECT 'Data load complete.' as status;

